spring.application.name=tp-github-api
server.port=8080

# En Linux/Mac: export GITHUB_TOKEN=ghp_xxxxxxxxxxxx
# En Windows (PowerShell): $env:GITHUB_TOKEN="ghp_xxxxxxxxxxxx"
github.api.base-url=https://api.github.com
github.api.version=2022-11-28
github.api.token=${GITHUB_TOKEN}
